# Generated by Django 4.2 on 2023-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_yea', models.CharField(max_length=50)),
                ('intensity', models.IntegerField(max_length=20)),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('start_year', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('added', models.CharField(max_length=50)),
                ('published', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pestle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('likelihood', models.IntegerField(max_length=20)),
            ],
        ),
    ]
