# Generated by Django 4.2 on 2023-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='insight',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
