# Generated by Django 4.2 on 2023-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_data_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.CharField(max_length=20),
        ),
    ]
