# Generated by Django 4.2 on 2023-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_data_likelihood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='end_yea',
            new_name='end_year',
        ),
        migrations.AddField(
            model_name='data',
            name='relevence',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
