# Generated by Django 4.2 on 2023-11-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_end_yea_data_end_year_data_relevence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='relevence',
            new_name='relevance',
        ),
    ]
